server:
  port: 8081
  
spring:
  application:
    name: config-service
    
  cloud:
    config:
      server:
        git:
          default-label: config-server   اسم الفرع االذي حملنا فيه الملف في GitHub
          uri: https://github.com/Baya91/Cour_Microservice_Es
          search-paths: config-data  
      
